# frontend/Dockerfile
# step 1: Build
FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install @vue/cli-service --save-dev
RUN npm install
COPY . .
RUN npm run build

# step 2: run with NGINXi
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]